version: '3.3'

services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
